### PR TITLE
front end redesign

### PR DESCRIPTION
**Pull request by matikin9**
Threw in Bootstrap styles using the Bootswatch Lumen theme (https://bootswatch.com/lumen/).

Re-organized the data a bit to filter for `TrpType == 'Regular'`, convert `TrpRoute` to integers, and then group by those integer `TrpRoute` values so they can be looped through in order.

Needs some further refactoring and clean-up.

### CODE REVIEW

**Comment by albertkun** [comment]
Looks good @matikin9 ! But waiting to see the application of the USWDS 👀

**Comment by albertkun** [comment]
Will merge this after we close #8 !

**Comment by matikin9** [comment]
@albertkun - I merged the other branch in to this one and removed some of the extra components.  It should be ready to push live now.

**Comment by albertkun** [comment]
@matikin9 Looks great!

**Pull request merged**
